### ISSUE TITLE
KidMentorSchedules - As a Admin I want to see only selected weekday

### ISSUE THREAD

**Issue by macrozone** [panterch/future_kids#111]
It should be possible to show only certain weekdays in the calendar, when comparing mentors. this can be done with checkboxes. Initially, it would select all weekdays, showing the whole week.
When fewer days are shown, they can be wider, which increase readability, if a lot of mentors are shown.

With this change, we can increase MAX_MENTORS_TO_DISPLAY (10 currently), because a user could "zoom" to one weekday.

**Comment by eigenmannmartin** [comment]
Now you can click on to the weekday's label to hide the column.
I figured the best is to leave the column visible to the user - so no one gets confused.

![selection_002](https://cloud.githubusercontent.com/assets/2293142/10997555/443eba1e-848e-11e5-9096-52d035441932.png)
