### ISSUE TITLE
Timestamps saved via React are rendered wrong

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#113]
Compare Timestamps are rendered wrong in form. Example mentor form:

<img width="683" alt="screen shot 2015-08-05 at 17 59 53" src="https://cloud.githubusercontent.com/assets/15120/9090651/cfa7dd60-3b9b-11e5-8d4a-5a23d086f1bf.png">

**Comment by macrozone** [comment]
It happens also when saved from the kid's edit-form directly, so it is a display issue in general.
