### ISSUE TITLE
Run js tests using phantomjs instead of firefox

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#115]

**Comment by qbrossard** [comment]
Basically phantomjs and the poltergeist driver do not support javascript alert boxes natively. You can then either use selenium only for these test cases or use some workaround (see https://gist.github.com/michaelglass/8610317 and various poltergeist issues with long threads). See this issue too for more discussion: https://github.com/teampoltergeist/poltergeist/issues/80

**Comment by panterch** [comment]
https://github.com/panterch/future_kids/tree/issue115
