### ISSUE TITLE
Fix Travis with newer versions of selenium-webdriver

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#117]
https://travis-ci.org/panterch/future_kids

**Comment by eigenmannmartin** [comment]
Selenium-webdriver 2.48 now does not click elements that are not visible or clickable by a user.
See [here](https://github.com/SeleniumHQ/selenium/issues/1202) and [here](https://github.com/SeleniumHQ/selenium/issues/1234)

Possible Fix:
- downgrade to 2.47.1
- or scroll to element or make it clickable (increase canvas size)

**Comment by panterch** [comment]
It worked locally but broke travis: https://travis-ci.org/panterch/future_kids/builds/107644432

**Comment by panterch** [comment]
Still a problem, see https://github.com/panterch/future_kids/pull/141

**Comment by panterch** [comment]
Branch for reproduction: https://github.com/panterch/future_kids/tree/issue117
