### ISSUE TITLE
Ability to set secondary mentor on timetable

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#119]

**Comment by macrozone** [comment]
setting a secondary mentor on the timetable is possible: when the primary mentor is assigned and a user clicks on another mentor on the timetable, the mentor is assigned as secondary mentor. If both are assigned, user gets an error message.

There are some issues though, e.g. you don't see on the timetable the date and the time of an already assigned mentor:

see https://github.com/panterch/future_kids/issues/120
