### ISSUE TITLE
KidMentorSchedules -  As an admin I want to see the mentors and the dates that are already assigned to the kid in the schedule

### ISSUE THREAD

**Issue by macrozone** [panterch/future_kids#120]
Usually every kid has two mentors: a primary and a secondary mentor (in case the other is not available).  

If one of them is assigned, it should be graphically visible on the timetable.

**Comment by eigenmannmartin** [comment]
The already set meeting is indicated with stripes. But only if no secondary mentor is set.
We also might want to indicate the name of the mentor - for the sake of readability.

![selection_003](https://cloud.githubusercontent.com/assets/2293142/11069234/72931442-87d5-11e5-861d-c3ac05e8ff97.png)
