### ISSUE TITLE
Use encrypted secrets

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#172]
http://edgeguides.rubyonrails.org/5_1_release_notes.html#encrypted-secrets

bin/rails secrets:setup

**Comment by toupeira** [comment]
This is already deprecated in Rails 5.2 and replaced by a new "credentials" system, see https://www.engineyard.com/blog/rails-encrypted-credentials-on-rails-5.2

Unfortunately they didn't support [multiple environments](https://github.com/rails/rails/issues/31349) at first, then went back and [added them](https://github.com/rails/rails/pull/33521) but only for Rails 6.0, and there's also a [rails-env-credentials](https://github.com/sinsoku/rails-env-credentials) gem to get something similar-but-not-exactly-the-same with Rails 5.x :grimacing:

Do you want to wait for Rails 6.0 or use the gem in the meantime?

**Comment by panterch** [comment]
I think we can wait ;-)
