### ISSUE TITLE
Link zur Stadt Zürich funktioniert nicht mehr (404)

### ISSUE THREAD

**Issue by rruettimann** [panterch/future_kids#195]
broken: https://www.stadt-zuerich.ch/content/aoz/de/index/integration/future_kids/angebot.html

funktioniert: https://www.stadt-zuerich.ch/aoz/de/index/integration/future_kids.html

<img width="1381" alt="screen shot 2018-02-27 at 13 10 46" src="https://user-images.githubusercontent.com/13944423/36728033-aae7f53a-1bbf-11e8-8011-b0b7f9af7565.png">

**Comment by panterch** [comment]
Danke, fixed.
