### ISSUE TITLE
Create a friendly CONTRIBUTING file

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#200]

**Comment by Barathwaja** [comment]
Can you guide me through the tech stack and process to install this so that i can prepare a contribution file for your repo.

**Comment by panterch** [comment]
The app is based on ruby on rails and mostly everything is uptodate. Most rails applications are installed in a standard way, if you are completly new to rails reading through the guides may help https://guides.rubyonrails.org/getting_started.html

The project has the following dependencies: Postgresql, ImageMagick. Also it needs ruby installed, preferrably with the rbenv wrapper. The  ruby version is specified in .ruby-version.

After downloading the repo and setting up the dependecies the setup should be:

```
bundle install
bundle exec rake db:create db:migrate db:seed
bundle exec rails server
```

For contributions it would also be nice to have a automated tests included and running test suite.

**Comment by Barathwaja** [comment]
Cool . !! let me do that.

**Comment by Barathwaja** [comment]
PR #206  .
