### ISSUE TITLE
Introduce status for teachers and mentors

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#251]
- Neu erfasst
- Warteschleife
- Zur Schulung eingeladen
- Zusage
- Absage

On /mentors and /teachers there should be a filter on state.

The field is settable only for admins, not for mentors. Please protect it via the mechanism found in https://github.com/panterch/future_kids/blob/530390b848002ecb0e5e96b9d0158745f2bf7ec1/app/controllers/application_controller.rb#L38

**Comment by luki215** [comment]
Also secure that user can log in only if in `Zusage` state. 
When #279 gets merged, user still can log in thanks to the "reset password" feature.
