### ISSUE TITLE
Improve EMail Texts

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#296]
![grafik](https://user-images.githubusercontent.com/15120/119226798-40bb8e80-bb0b-11eb-9a26-7f76bd6bf744.png)

![grafik](https://user-images.githubusercontent.com/15120/119228097-b1fe4000-bb11-11eb-9a09-74c6f984bb2a.png)

![grafik](https://user-images.githubusercontent.com/15120/119675413-4e3f8400-be3d-11eb-8be0-635c0a9248a9.png)

![grafik](https://user-images.githubusercontent.com/15120/119675461-5ac3dc80-be3d-11eb-8af1-064e1e3f7f56.png)

![grafik](https://user-images.githubusercontent.com/15120/119675336-3c5de100-be3d-11eb-99bc-fd77903709ae.png)

**Comment by alesrosina** [comment]
Fixed directly on heroku instance, where env var `APP_DOMAIN` was wrongly set to panter.ch
