### ISSUE TITLE
Additional schools

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#302]
In https://github.com/panterch/future_kids/issues/273 we did an import of primary schools.

Please find attached some more schools. The import should work the same for them, only difference is that school_type should be "Gymnasium".

Please also import directly on dev and prod instance of this project.

[Stadtzürcher Gymnasien_öffentliche_anerkannte private.xlsx](https://github.com/panterch/future_kids/files/6546683/Stadtzurcher.Gymnasien_offentliche_anerkannte.private.xlsx)

**Comment by mojpanter** [comment]
```
wget https://gist.githubusercontent.com/mojpanter/db213ce09ef94aac3fba97aa9ce97748/raw/c0baefbdfb2690598f689425059b80fb88809b56/additional_import.rb
wget https://gist.githubusercontent.com/mojpanter/4c690c2d278f90124cb23c780e02ade9/raw/cefcc9196d708ddbafe04f895febe2f7e7536f80/additional_import.csv
rails runner additional_import.rb
```
