### ISSUE TITLE
Rails 7 Upgrade

### ISSUE THREAD

**Issue by panterch** [panterch/future_kids#326]

**Comment by CodeWAdi** [comment]
I'm kinda new in here in github can you please explain me what i have to do to close this issue

**Comment by panterch** [comment]
> I'm kinda new in here in github can you please explain me what i have to do to close this issue

Thanks for your support, much appreciated!

There's a contribution guide inside the project repository: https://github.com/panterch/future_kids/blob/master/CONTRIBUTING.md
